[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#7B1FA2"
backgroundColor = "#F3E5F5"
secondaryBackgroundColor = "#ffffff"
textColor = "#4A148C"
font = "sans serif"

[server]
headless = true
